//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USQLCSharpProject1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Description { get; set; }
        public string AdditionInfo { get; set; }
        public string FinePrintInfo { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductSubCategoryId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public Nullable<int> DiscountRate { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public bool IsActivated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastUpdatedAt { get; set; }
        public Nullable<System.Guid> LastUpdatedByUser { get; set; }
        public Nullable<int> TotalBought { get; set; }
        public string Remarks { get; set; }
        public bool IsPublished { get; set; }
        public string ImageFolderUrl { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
    }
}
